### ISSUE TITLE
Handle nil pointer when initializing global variable repository

### ISSUE THREAD

**Issue by htrmind7** [myrteametrics/myrtea-engine-api#168]
When initliazing global variable, if the related table does not exist, engine panics

{"level":"info","ts":"2024-02-08T06:03:07.849+0100","caller":"referential/global_variables.go:95","msg":"Fetching global variables"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x899094]

goroutine 1 [running]:
github.com/myrteametrics/myrtea-engine-api/v5/internals/variablesconfig.(*PostgresRepository).newStatement(0xc000014aa0)
        /home/hantran/go/pkg/mod/github.com/myrteametrics/myrtea-engine-api/v5@v5.3.5/internals/variablesconfig/postgres_repository.go:32 +0x94
github.com/myrteametrics/myrtea-engine-api/v5/internals/variablesconfig.(*PostgresRepository).GetAllAsMap(0x2237000?)
        /home/hantran/go/pkg/mod/github.com/myrteametrics/myrtea-engine-api/v5@v5.3.5/internals/variablesconfig/postgres_repository.go:188 +0x65
github.com/myrteametrics/myrtea-connector-kafka-colissimo-qssla/internals/referential.(*GlobalVariables).Load(0xc00017d0e0)
        /home/hantran/Documents/github/myrtea-connector-kafka-colissimo-qssla/internals/referential/global_variables.go:100 +0xc4
github.com/myrteametrics/myrtea-connector-kafka-colissimo-qssla/internals/job.FetchReferentialJob.Run({{0xc00004aba0, 0x22}, {0xc00004acc0, 0x26}, {0xc000033660, 0x10}})
        /home/hantran/Documents/github/myrtea-connector-kafka-colissimo-qssla/internals/job/fetch_referential.go:25 +0x3c
main.main()
        /home/hantran/Documents/github/myrtea-connector-kafka-colissimo-qssla/main.go:82 +0x7c6

**Comment by Ismail731404** [comment]
The problem is caused by the repository not being initialized when it is used as a dependency. It is necessary to initialize the repository when using this project as a dependency.
