### ISSUE TITLE
Support asynchronous requests on /aggregates (similar to ingester /ingest)

### ISSUE THREAD

**Issue by cedricablain** [myrteametrics/myrtea-engine-api#75]
- Mise en place d'une queue
- Mise en place de la consommation de la queue (par le traitement actuellement dans le endpoint)
- Mise en place d'un renvoie de statut HTTP 429 (si la queue est full ou presque)

**Comment by SchawnnDev** [comment]
Process all aggregates in one goroutine with a processing queue or in multiple goroutines (balanced worker system) ?

**Comment by SchawnnDev** [comment]
Added in 7b4bf7fc4661897e70310d1fc09ef76831c4bcd0 (#93)
