### ISSUE TITLE
Situation reporting action : can export more than 10k rows

### ISSUE THREAD

**Issue by htrmind7** [myrteametrics/myrtea-engine-api#90]
Currently the ExportFactHits function doesn't seem to work when the number of hits exceed 10000 (default limit of elastic).

In some cases, especially for some reports in Rapport Express, users need their csv reports with more than 10k rows, which we can't offer yet. Manual scripts outside myrtea are put in place to work around temporarily.

**Comment by SchawnnDev** [comment]
works in elastic > 6

**Comment by SchawnnDev** [comment]
Export only works in elastic > 6.
